# Plan: Expand WASM Boundary Contract — Fixture Coverage Serial Sequence II

## Context

The first fixture wave validated core compiler/runtime bring-up (gates 1–13) and demo-behavior expression. The next gap is **engine stress coverage**: dispatch modes, typing edges, multi-pass ordering, contention, resize/hotswap correctness, and integrated orchestration.

`// [LAW:verifiable-goals] Every gate below has a deterministic pass/fail condition.`  
`// [LAW:one-source-of-truth] Each fixture is a canonical payload in the fixture registry, with one dedicated smoke assertion path.`  
`// [LAW:dataflow-not-control-flow] Validation runs the same install→tick→sample flow for every fixture; only fixture data varies.`

### What This New Sequence Covers
- `dispatch-exact-2d`
- `dispatch-texture-footprint`
- `type-cast-matrix`
- `control-flow-nested`
- `varying-type-matrix`
- `multi-draw-single-pass`
- `texture-pingpong-heat`
- `stream-driven-spectral-field`
- `atomic-histogram`
- `resize-canvas-relative-chain`
- `hotswap-preserve-state-proof`
- `full-stack-orchestration`

---

## Gate Sequence

### Gate 14: Exact 2D Dispatch
**Unlocks:** Verified non-domain compute scheduling.  
**What:** Exercise `DispatchMode::Exact` with `global_invocation_id.x/y`.  
**Files:**
- `src/render/rust/fixtures/dispatch-exact-2d.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs` (fixture-specific checker branch)  
**Fixture:** `dispatch-exact-2d` — writes checkerboard into storage texture, sampled fullscreen.  
**Gate test:** Cell pattern hash matches expected for fixed `(x,y)` dispatch.

### Gate 15: Texture-Driven Dispatch Footprint
**Unlocks:** Correct texture-mode thread footprint and edge handling.  
**What:** Exercise `DispatchMode::Texture` against non-square texture extents.  
**Files:**
- `src/render/rust/fixtures/dispatch-texture-footprint.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`  
**Fixture:** `dispatch-texture-footprint` — writes UV gradient + explicit 1px border marker.  
**Gate test:** Border pixels exactly match expected marker values.

### Gate 16: Cast and Type Matrix
**Unlocks:** Confidence in cast semantics across scalar types.  
**What:** Stress `f32/u32/i32/bool` cast/compare round-trips.  
**Files:**
- `src/render/rust/fixtures/type-cast-matrix.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`  
**Fixture:** `type-cast-matrix` — computes per-lane bitmask from cast outcomes and visualizes it.  
**Gate test:** Scalar checksum equals golden value.

### Gate 17: Nested Control Flow
**Unlocks:** Robust loop/branch lowering under nesting pressure.  
**What:** Nested `For + If + Break + Continue + Var/Assign`.  
**Files:**
- `src/render/rust/fixtures/control-flow-nested.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`  
**Fixture:** `control-flow-nested` — procedural stripe/band field generated by nested loops.  
**Gate test:** Band count and checksum match baseline.

### Gate 18: Varying Type Matrix
**Unlocks:** Inter-stage transport confidence for multiple varying shapes.  
**What:** Pass and consume `f32/vec2/vec3/vec4` varyings with swizzle/index usage.  
**Files:**
- `src/render/rust/fixtures/varying-type-matrix.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`  
**Fixture:** `varying-type-matrix` — vertex emits multiple channels, fragment recombines deterministically.  
**Gate test:** Pixel probes at fixed UVs match expected channel values.

### Gate 19: Multi-Draw Single Render Pass
**Unlocks:** Stable ordering and dependency separation in one render pass.  
**What:** 3 draw calls in one pass, each with distinct domain inputs.  
**Files:**
- `src/render/rust/fixtures/multi-draw-single-pass.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`  
**Fixture:** `multi-draw-single-pass` — background grid, mid sprites, foreground points.  
**Gate test:** Layer ordering deterministic across repeated captures.

### Gate 20: Texture Ping-Pong Heat
**Unlocks:** Multi-pass texture read/write stability.  
**What:** Two-texture ping-pong compute update, sampled in final render.  
**Files:**
- `src/render/rust/fixtures/texture-pingpong-heat.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`  
**Fixture:** `texture-pingpong-heat` — diffusion/decay style simulation.  
**Gate test:** Total energy metric decays monotonically across N ticks.

### Gate 21: Stream-Driven Spectral Field
**Unlocks:** High-frequency stream ingestion correctness.  
**What:** Drive per-frame compute from `update_data_stream` (256 bins).  
**Files:**
- `src/render/rust/fixtures/stream-driven-spectral-field.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`
- `scripts/push-fixture-stream-frames.mjs`  
**Fixture:** `stream-driven-spectral-field` — radial field amplitude/color from stream bins.  
**Gate test:** Deterministic stream sequence yields deterministic checksum sequence.

### Gate 22: Atomic Histogram
**Unlocks:** Atomic correctness under heavy contention.  
**What:** Bin 4k particles into 256 counters with atomics; render histogram.  
**Files:**
- `src/render/rust/fixtures/atomic-histogram.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`  
**Fixture:** `atomic-histogram` — compute histogram + draw bars.  
**Gate test:** `sum(counters) == particle_count` each frame.

### Gate 23: Resize Canvas-Relative Chain
**Unlocks:** Reliable resize without reinstall for texture chains.  
**What:** Reallocate only `relativeTo: canvas` textures used in chained passes.  
**Files:**
- `src/render/rust/fixtures/resize-canvas-relative-chain.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`
- `scripts/check-payload-resize-sequence.mjs`  
**Fixture:** `resize-canvas-relative-chain` — two intermediates sampled in final pass.  
**Gate test:** Resize script shows continuous rendering and zero reinstall events.

### Gate 24: Hot-Swap Preserve-State Proof
**Unlocks:** Verified state continuity through reinstall.  
**What:** Reinstall with changed shader math under `preserveStateOnRecompile=true`.  
**Files:**
- `src/render/rust/fixtures/hotswap-preserve-state-proof.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`
- `scripts/check-hotswap-preserve-state.mjs`  
**Fixture:** `hotswap-preserve-state-proof` — long-running sim where position state must persist.  
**Gate test:** Position buffer hash unchanged pre/post reinstall; color output changes.

### Gate 25: Full-Stack Orchestration
**Unlocks:** Release-level confidence across all exercised subsystems.  
**What:** Integrate domains + textures + samplers + streams + atomics + varyings + derivatives + resize + hotswap.  
**Files:**
- `src/render/rust/fixtures/full-stack-orchestration.ts`
- `src/render/rust/fixtures/index.ts`
- `scripts/check-payload-tester-visible.mjs`
- `scripts/check-full-stack-orchestration.mjs`  
**Fixture:** `full-stack-orchestration` — layered scene with reactive particles, ping-pong field, atomic HUD, AA overlay.  
**Gate test:** 300-tick scripted run + resize + hotswap completes with no diagnostics and invariant checks passing.

---

## Summary: Linear Fixture Sequence II

| # | Gate | Key Capability Added | Fixture |
|---|------|----------------------|---------|
| 14 | Exact 2D Dispatch | Non-domain compute scheduling | `dispatch-exact-2d` |
| 15 | Texture Dispatch Footprint | Texture-mode bounds correctness | `dispatch-texture-footprint` |
| 16 | Cast/Type Matrix | Scalar type conversion correctness | `type-cast-matrix` |
| 17 | Nested Control Flow | Complex branching/loop lowering | `control-flow-nested` |
| 18 | Varying Type Matrix | Multi-type inter-stage transport | `varying-type-matrix` |
| 19 | Multi-Draw Single Pass | Ordering + dependency isolation | `multi-draw-single-pass` |
| 20 | Texture Ping-Pong | Multi-pass texture R/W stability | `texture-pingpong-heat` |
| 21 | Stream Spectral Field | Deterministic stream ingestion | `stream-driven-spectral-field` |
| 22 | Atomic Histogram | Contended atomic correctness | `atomic-histogram` |
| 23 | Resize Texture Chain | Canvas-relative resize continuity | `resize-canvas-relative-chain` |
| 24 | Hot-Swap State Proof | Reinstall without state loss | `hotswap-preserve-state-proof` |
| 25 | Full-Stack Orchestration | End-to-end integrated reliability | `full-stack-orchestration` |

**After Gate 18**, shader-language and inter-stage transport coverage is complete.  
**After Gate 22**, compute correctness under contention and streaming is validated.  
**After Gate 25**, the engine has production-grade integration coverage across all major subsystems.
