export EPOCH=$(date +%s)

id0=$(pnpm exec lnks new --topic phase-0 --type epic --title "PHASE 0 EPIC: The Brutal Hardening (Burn the Ships)" --description "This Epic precedes all new architectural work. Its sole purpose is to ruthlessly delete legacy fallbacks, deprecated blocks, and tests that enforce obsolete behavior.

If we leave legacy code or tests intact, the autonomous agents will inevitably wire the new architecture into the old fallbacks to make the tests pass, structurally corrupting the engine.

Key Objectives:
1. Delete all tests that assert legacy memory layouts, string concatenation, or non-canonical render semantics.
2. Remove any fallback paths in the Rust renderer or TS compiler that allow non-canonical execution.
3. Purge the block library of components that inherently violate the upcoming Symbolic Memory or Decoupled Domain architectures." | grep -o 'lit-[^ ]*' | head -1)

id0_1=$(pnpm exec lnks new --topic phase-0-tests --type task --title "Purge tests asserting legacy TS memory layouts and string concatenation" --description "Goal:
- Delete any unit test that actively prevents the TS compiler from yielding memory ownership to Rust.

Scope:
- Find and delete tests in \`src/compiler/backend/__tests__\` or similar that assert exact byte offsets, \`std140\` padding calculations, or \`stride\` math generated by TypeScript.
- Delete tests that assert the generation of raw WGSL strings from blocks (e.g., tests checking for \`const PARAM_OFFSET = 123u;\`).

Why:
- If we do not delete these tests, the agent tasked with building the Symbolic Memory Manifest will write horrific hacks to keep these tests passing, defeating the purpose of the refactor.

Acceptance:
- \`pnpm test\` passes because the restrictive tests are physically removed." | grep -o 'lit-[^ ]*' | head -1)

id0_2=$(pnpm exec lnks new --topic phase-0-fluid-purge --type task --title "Delete fluid-gpu-bundle.ts and associated WGSL string injection" --description "Goal:
- Ruthlessly delete the ad-hoc fluid implementation that relies on TS-side WGSL string concatenation and hardcoded byte offsets.

Scope:
- Delete \`src/services/fluid-gpu-bundle.ts\`.
- Remove any compiler hooks that call into it.
- Remove legacy fluid blocks (\`FluidDynamics2D\`, \`FluidSplat\`, etc.) from the block registry. 

Why:
- We are moving to a Native Compute Kernel Dispatch model. If this file exists, the agent will try to adapt the Symbolic Memory Manifest to support string concatenation, completely corrupting the architecture. We will rebuild fluids later on top of the correct foundation.

Acceptance:
- The file is gone, the blocks are unregistered, and the compiler no longer attempts to inject raw WGSL compute passes." | grep -o 'lit-[^ ]*' | head -1)

id0_3=$(pnpm exec lnks new --topic phase-0-constantpatcher --type task --title "Delete ConstantPatcher.ts and legacy parameter injection" --description "Goal:
- Remove the system that attempts to hot-swap constants by modifying the compiled IR and triggering re-uploads.

Scope:
- Delete \`src/services/ConstantPatcher.ts\`.
- Remove the UI hooks that call it. The UI should temporarily fall back to triggering a standard full-graph recompile on slider moves (we will fix the UX in Phase 1 with the Live Parameter fast-path).

Why:
- The presence of this file will confuse the agent building the Live Control Buffer, leading to dual-path parameter updates.

Acceptance:
- \`ConstantPatcher.ts\` is deleted and the application still functions (albeit with recompiles on slider scrubs)." | grep -o 'lit-[^ ]*' | head -1)

id0_4=$(pnpm exec lnks new --topic phase-0-block-purge --type task --title "Purge blocks violating Decoupled Domains" --description "Goal:
- Pre-emptively remove blocks that fuse domain generation with physical spatial mapping.

Scope:
- Delete \`GridBasis\`, \`SpiralBasis\`, and any other block that physically allocates a \`uv\` field without explicitly mapping a 1D domain to 2D space.
- Update demo patches to temporarily break or use fallback logic.

Why:
- We are replacing this with \`InstanceDomain\`. If the old blocks exist, the agent will try to make the new system backward-compatible with physical UV allocation, ruining the zero-allocation requirement.

Acceptance:
- The old basis blocks are removed from the registry." | grep -o 'lit-[^ ]*' | head -1)

pnpm exec lnks parent set $id0_1 $id0
pnpm exec lnks parent set $id0_2 $id0
pnpm exec lnks parent set $id0_3 $id0
pnpm exec lnks parent set $id0_4 $id0

echo "Phase 0 created"
