/**
 * ══════════════════════════════════════════════════════════════════════
 * VALUEEXPR SCALAR EVALUATOR
 * ══════════════════════════════════════════════════════════════════════
 *
 * Scalar evaluation for the unified ValueExpr table.
 * This evaluator handles scalar-extent ValueExpr nodes (cardinality one,
 * temporality continuous).
 *
 * ──────────────────────────────────────────────────────────────────────
 * IMPORTANT: SCALAR-EXTENT ONLY
 * ──────────────────────────────────────────────────────────────────────
 *
 * This evaluator handles ONLY scalar-extent expressions:
 * - Cardinality: one (not zero, not many)
 * - Temporality: continuous (not discrete)
 *
 * Field-extent (cardinality many) → Materializer
 * Event-extent (temporality discrete) → ValueExprEventEvaluator
 *
 * Runtime assertions enforce this constraint.
 *
 * ══════════════════════════════════════════════════════════════════════
 */

import type { ValueExpr } from '../compiler/ir/value-expr';
import type { ValueExprId } from '../compiler/ir/Indices';
import type { RuntimeState } from './RuntimeState';
import { recordNaN, recordInfinity } from './HealthMonitor';
import { constValueAsNumber } from '../core/canonical-types';
import { applyPureFn } from './ScalarKernelLibrary';

export interface ScalarEvalContext {
  evaluateReduceKernel?: (
    expr: Extract<ValueExpr, { kind: 'kernel'; kernelKind: 'reduce' }>,
    valueExprs: readonly ValueExpr[],
    state: RuntimeState
  ) => number;
}

/**
 * Evaluate a construct expression and write all components contiguously to a buffer
 *
 * @param expr - Construct ValueExpr node
 * @param valueExprs - Dense array of ValueExpr nodes
 * @param state - Runtime state
 * @param targetBuffer - Target numeric buffer (Float32Array or Float64Array)
 * @param targetOffset - Starting offset in buffer
 * @returns Number of components written (stride)
 */
export function evaluateConstructScalar(
  expr: Extract<ValueExpr, { kind: 'construct' }>,
  valueExprs: readonly ValueExpr[],
  state: RuntimeState,
  targetBuffer: Float32Array | Float64Array,
  targetOffset: number,
  context?: ScalarEvalContext
): number {
  // Evaluate each component and write contiguously
  for (let i = 0; i < expr.components.length; i++) {
    const componentValue = evaluateValueExprScalar(expr.components[i], valueExprs, state, context);
    targetBuffer[targetOffset + i] = componentValue;
  }
  return expr.components.length;
}

/**
 * Evaluate a scalar ValueExpr with caching
 *
 * @param veId - ValueExpr ID to evaluate
 * @param valueExprs - Dense array of ValueExpr nodes
 * @param state - Runtime state with cache
 * @returns Evaluated scalar value
 */
export function evaluateValueExprScalar(
  veId: ValueExprId,
  valueExprs: readonly ValueExpr[],
  state: RuntimeState,
  context?: ScalarEvalContext
): number {
  // Check cache first
  const cached = state.cache.scalarValueExprValues[veId as number];
  const cachedStamp = state.cache.scalarValueExprStamps[veId as number];
  if (cachedStamp === state.cache.frameId) {
    return cached;
  }

  // Get expression from dense array
  const expr = valueExprs[veId as number];
  if (!expr) {
    throw new Error(`ValueExpr ${veId} not found`);
  }

  // Evaluate based on kind
  const value = evaluateScalarExtent(expr, valueExprs, state, context);

  // NaN/Inf detection (batched)
  // Note: sourceBlockId not yet tracked in IR - will pass null for now
  // Once IR includes block provenance, update this to pass actual block ID
  if (Number.isNaN(value)) {
    recordNaN(state, null);
  } else if (!Number.isFinite(value)) {
    // Infinity (positive or negative)
    recordInfinity(state, null);
  }

  // Cache result
  state.cache.scalarValueExprValues[veId as number] = value;
  state.cache.scalarValueExprStamps[veId as number] = state.cache.frameId;

  return value;
}

/**
 * Evaluate a scalar-extent ValueExpr recursively
 *
 * @param expr - ValueExpr to evaluate
 * @param valueExprs - Dense array of all ValueExpr nodes (for recursive evaluation)
 * @param state - Runtime state
 * @returns Evaluated value
 */
function evaluateScalarExtent(
  expr: ValueExpr,
  valueExprs: readonly ValueExpr[],
  state: RuntimeState,
  context?: ScalarEvalContext
): number {
  if (!state.time) {
    throw new Error('Effective time not set');
  }

  switch (expr.kind) {
    case 'const': {
      return constValueAsNumber(expr.value);
    }

    // REMOVED 2026-02-06: slotRead case - dead code
    // SlotRead expressions are never generated by the compiler.
    // Extract handles component access via recursive evaluation.

    case 'time': {
      switch (expr.which) {
        case 'tMs':
          return state.time.tMs;
        case 'dt':
          return state.time.dt;
        case 'phaseA':
          return state.time.phaseA;
        case 'phaseB':
          return state.time.phaseB;
        case 'progress':
          return state.time.progress !== undefined ? state.time.progress : 0;
        case 'palette':
          // Palette is stored in objects map at reserved slot 0
          return 0; // Slot number for palette
        case 'energy':
          return state.time.energy;
        default: {
          const _exhaustive: never = expr.which;
          throw new Error(`Unknown time channel: ${String(_exhaustive)}`);
        }
      }
    }

    case 'external': {
      return state.externalChannels.snapshot.getFloat(expr.channel);
    }

    case 'kernel': {
      return evaluateKernelScalar(expr, valueExprs, state, context);
    }

    case 'state': {
      // Read from persistent state array using resolved physical slot
      if (expr.resolvedSlot === undefined) {
        throw new Error(`State expression for key "${expr.stateKey}" has no resolved slot — binding pass may not have run`);
      }
      return state.state[expr.resolvedSlot as number];
    }

    case 'shapeRef': {
      // [LAW:no-silent-fallbacks] Shape references are non-numeric resources.
      // Evaluating them as scalar numbers would mask schedule bugs.
      throw new Error('ShapeRef expressions are not scalar-evaluable; evaluate via shape2d write path');
    }

    case 'eventRead': {
      // Read event scalar as float: 0 → 0.0, 1 → 1.0 (spec §9.2)
      const scalar = state.eventScalars[expr.eventSlot as number];
      return scalar !== undefined ? scalar : 0;
    }

    case 'intrinsic': {
      const intrinsicName = expr.intrinsicKind === 'property' ? expr.intrinsic : expr.field;
      throw new Error(`Intrinsic expressions are field-extent, not scalar-extent (intrinsic=${intrinsicName})`);
    }

    case 'event': {
      throw new Error('Event expressions must be evaluated by ValueExprEventEvaluator');
    }

    case 'extract': {
      // [LAW:one-source-of-truth] Multi-component scalar expressions live in arena slots.
      // Read directly from the materialized slot — schedule ordering guarantees
      // the input was written before this extract evaluates.
      const scalarExprToArenaOffset = state.cache.scalarExprToArenaOffset;
      const offset = scalarExprToArenaOffset?.get(expr.input as number);
      if (offset === undefined) {
        const inputExpr = valueExprs[expr.input as number];
        if (!inputExpr) {
          throw new Error(
            `extract(${expr.componentIndex}): input ${expr.input} not found in ValueExpr table`
          );
        }

        // [LAW:single-enforcer] Structural extract-from-construct is handled directly
        // here; all other extract addressability is enforced at schedule construction.
        if (inputExpr.kind === 'construct') {
          const componentExpr = inputExpr.components[expr.componentIndex];
          if (componentExpr === undefined) {
            throw new Error(
              `extract(${expr.componentIndex}): input ${expr.input} has only ${inputExpr.components.length} components`
            );
          }
          return evaluateValueExprScalar(componentExpr, valueExprs, state, context);
        }

        throw new Error(
          `extract(${expr.componentIndex}): input ${expr.input} has no slot mapping`
        );
      }
      return state.arena[offset + expr.componentIndex];
    }

    case 'construct': {
      // Construct evaluates component expressions and returns the first component's value.
      // For multi-component scalar expressions (vec2, vec3, color), the evaluator is responsible
      // for writing ALL components contiguously when this expression is used as a step target.
      // When construct is evaluated recursively (not as a step root), we return component[0].
      if (expr.components.length === 0) {
        throw new Error('construct expression has no components');
      }
      // Return first component value (caller may write all components if this is a step root)
      return evaluateValueExprScalar(expr.components[0], valueExprs, state, context);
    }

    case 'hslToRgb': {
      // HSL→RGB is field-extent only.
      throw new Error('hslToRgb expressions are field-extent, not scalar-extent');
    }

    default: {
      const _exhaustive: never = expr;
      throw new Error(`Unknown ValueExpr kind: ${(_exhaustive as ValueExpr).kind}`);
    }
  }
}

/**
 * Evaluate kernel operations for scalar-extent expressions
 *
 * @param expr - Kernel ValueExpr
 * @param valueExprs - Dense array of ValueExpr nodes
 * @param state - Runtime state
 * @returns Evaluated value
 */
function evaluateKernelScalar(
  expr: Extract<ValueExpr, { kind: 'kernel' }>,
  valueExprs: readonly ValueExpr[],
  state: RuntimeState,
  context?: ScalarEvalContext
): number {
  switch (expr.kernelKind) {
    case 'map': {
      // Unary kernel: fn(input)
      const inputVal = evaluateValueExprScalar(expr.input, valueExprs, state, context);
      return applyPureFn(expr.fn, [inputVal]);
    }

    case 'zip': {
      // N-ary kernel: fn(inputs...)
      const inputVals = expr.inputs.map(id => evaluateValueExprScalar(id, valueExprs, state, context));
      return applyPureFn(expr.fn, inputVals);
    }

    case 'zipPromote': {
      // zipPromote is field-extent only (requires field input)
      throw new Error('zipPromote kernels are field-extent, not scalar-extent');
    }

    case 'broadcast': {
      // Broadcast is one → many (changes cardinality to many)
      throw new Error('broadcast kernels are field-extent, not scalar-extent');
    }

    case 'reduce': {
      // [LAW:one-source-of-truth] Reduce evaluation strategy is injected by the
      // active executor/materializer context so scalar evaluation has one canonical
      // reduce path rather than ad hoc fallback logic.
      if (!context?.evaluateReduceKernel) {
        throw new Error('reduce kernels require scalar evaluation context');
      }
      return context.evaluateReduceKernel(expr, valueExprs, state);
    }

    case 'pathDerivative': {
      // PathDerivative is field-extent only
      throw new Error('pathDerivative kernels are field-extent, not scalar-extent');
    }

    case 'pathSample': {
      // PathSample is field-extent only (cross-instance sampling)
      throw new Error('pathSample kernels are field-extent, not scalar-extent');
    }

    default: {
      const _exhaustive: never = expr;
      throw new Error(`Unknown kernel kind: ${(_exhaustive as Extract<ValueExpr, { kind: 'kernel' }>).kernelKind}`);
    }
  }
}
