/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const attach_shared_input: (a: any) => [number, number];
export const attach_shared_shape_bank: (a: any) => [number, number];
export const attach_shared_sink_table: (a: any) => [number, number];
export const init_engine: (a: any, b: number, c: number, d: number, e: number, f: number) => any;
export const inject_poison_alloc: () => [number, number];
export const pause_engine: () => [number, number];
export const rebuild_gpu_pipelines: (a: any) => any;
export const resume_engine: () => [number, number];
export const set_debug_readback_hz: (a: number) => [number, number];
export const set_sink_pointer_map: (a: number, b: number) => [number, number];
export const take_frame_pacing_packet: () => [number, number, number];
export const take_readback_snapshot: () => [number, number, number];
export const upload_atlas_data: (a: any) => [number, number];
export const wasm_bindgen__closure__destroy__h34af7beb892ac90c: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hac389948b8d10e82: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h3a942a1bf5f19357: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h08519952343379dd: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hcb563ba53ad42ec8: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h1d4d9e8783fdfb62: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h65696f0a51e234e0: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h65696f0a51e234e0_3: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
