/**
 * Expression Block
 *
 * User-defined mathematical expressions compiled to IR via Expression DSL.
 * Provides flexible signal computation without creating new blocks.
 *
 * Architecture:
 * - Legacy inputs (in0, in1): Fixed optional inputs for backward compatibility
 * - Varargs refs input: Variable-length block references (NEW 2026-01-26)
 * - Payload-Generic inputs: Accept any concrete payload type
 * - Expression config parameter: Text string, not wirable
 * - Compilation: Delegated to Expression DSL (src/expr/)
 *
 * UNIFIED VARARGS SYSTEM (2026-01-26):
 * - SINGLE CODE PATH: Legacy in0/in1 AND varargs refs flow through ONE processing loop
 * - in0/in1 are shims: converted to synthetic vararg-style entries internally
 * - ALL inputs processed identically: build unified Map<string, SigExprId>
 * - No dual processing paths - ONE loop handles everything
 *
 * Design Decisions:
 * - ONE SOURCE OF TRUTH: Expression DSL is the sole compiler (no duplicate logic)
 * - SINGLE ENFORCER: Type checking happens once in expression compiler
 * - ISOLATION: Expression DSL stays in src/expr/, minimal integration surface
 */

import { registerBlock, ALL_CONCRETE_PAYLOADS } from './registry';
import { signalType, strideOf, FLOAT, INT, BOOL, VEC2, VEC3, COLOR, SHAPE, CAMERA_PROJECTION } from '../core/canonical-types';
import type { SignalType, PayloadType } from '../core/canonical-types';
import { compileExpression } from '../expr';
import type { SigExprId, SigExpr } from '../compiler/ir/types';

// =============================================================================
// Expression (Payload-Generic)
// =============================================================================

registerBlock({
  type: 'Expression',
  label: 'Expression',
  category: 'math',
  description: 'Compute signal from mathematical expression',
  form: 'primitive',
  capability: 'pure',
  cardinality: {
    cardinalityMode: 'preserve',
    laneCoupling: 'laneLocal',
    broadcastPolicy: 'allowZipSig',
  },
  payload: {
    allowedPayloads: {
      in0: ALL_CONCRETE_PAYLOADS,
      in1: ALL_CONCRETE_PAYLOADS,
      refs: ALL_CONCRETE_PAYLOADS,
      out: ALL_CONCRETE_PAYLOADS,
    },
    // Expression block has dynamic type resolution based on expression text
    // The output type depends on the expression, not a fixed combination
    semantics: 'typeSpecific',
  },

  // Inputs include both wirable ports AND config parameters
  // Config parameters have exposedAsPort: false
  inputs: {
    // Legacy fixed input ports (2 optional inputs)
    // Kept for backward compatibility - internally processed same as varargs
    // defaultSource auto-generated by registry (architectural law: all ports get defaults)
    in0: {
      label: 'In 0',
      type: signalType(FLOAT), // Default type - actual type inferred during lowering
      optional: true,            // Unwired inputs are unavailable in expression
      exposedAsPort: true,
    },
    in1: {
      label: 'In 1',
      type: signalType(FLOAT),
      optional: true,
      exposedAsPort: true,
    },
    // Varargs input port for block references (NEW 2026-01-26)
    // Accepts variable-length connections with aliases
    // Varargs cannot have defaultSource (explicit connections only)
    refs: {
      label: 'Block Refs',
      type: signalType(FLOAT),  // Base type for validation
      optional: true,
      exposedAsPort: true,
      isVararg: true,
      varargConstraint: {
        payloadType: FLOAT,
        cardinalityConstraint: 'any',  // Accept Signal or Field
      },
    },
    // Config parameter (not a port - cannot be wired)
    // Note: Inspector UI will detect Expression block and render this as multiline
    expression: {
      label: 'Expression',
      type: signalType(FLOAT),  // Config-only, type not used
      exposedAsPort: false,       // Config-only, not wirable
      value: '',                  // Default: empty expression
      uiHint: { kind: 'text' },   // Text input (Inspector will make it multiline)
    },
  },

  outputs: {
    out: {
      label: 'Output',
      type: signalType(FLOAT), // Default - actual type inferred during lowering
    },
  },

  /**
   * Lower Expression block to IR.
   *
   * UNIFIED VARARGS SYSTEM:
   * Step 1: SHIM - Convert legacy in0/in1 to synthetic vararg-style entries
   * Step 2: MERGE - Combine synthetic entries with actual varargs refs
   * Step 3: SINGLE LOOP - Process ALL inputs through ONE code path
   * Step 4: Compile with unified Map<string, SigExprId>
   *
   * Algorithm:
   * 1. Extract expression text from config
   * 2. Handle empty expression (output constant 0)
   * 3. Build unified input list (legacy + varargs)
   * 4. Single processing loop: build inputSignals map
   * 5. Call compileExpression() from Expression DSL
   * 6. Handle success: return output signal
   * 7. Handle error: throw CompileError with clear message
   *
   * Error Handling:
   * - Syntax errors: thrown by parser with position info
   * - Type errors: thrown by type checker with suggestions
   * - Undefined identifiers: lists available inputs
   */
  lower: ({ ctx, inputsById, varargInputsById, config }) => {
    // Step 1: Extract expression text from config
    const exprText = (config?.expression as string | undefined) ?? '';

    // Step 2: Handle empty expression (output constant 0)
    if (exprText.trim() === '') {
      const sigId = ctx.b.sigConst(0, signalType(FLOAT));
      const outType = ctx.outTypes[0];
      const slot = ctx.b.allocSlot();
      return {
        outputsById: {
          out: { k: 'sig', id: sigId, slot, type: outType, stride: strideOf(outType.payload) },
        },
      };
    }

    // Helper: Get actual type from signal expression
    // IRBuilder tracks types for all signal expressions
    const getSigType = (sigId: SigExprId): SignalType => {
      const sigExprs = ctx.b.getSigExprs();
      const sigExpr = sigExprs[sigId as number];
      if (!sigExpr) {
        throw new Error(`Signal expression ${sigId} not found - this indicates a compiler bug`);
      }
      return sigExpr.type;
    };

    // Step 3: Build unified input list
    // SHIM: Convert legacy inputs to synthetic vararg-style entries
    const allInputEntries: Array<{ alias: string; signal: SigExprId }> = [];

    // Legacy inputs (in0, in1) become synthetic vararg entries
    for (const key of ['in0', 'in1'] as const) {
      const input = inputsById[key];
      if (input && input.k === 'sig') {
        allInputEntries.push({ alias: key, signal: input.id as SigExprId });
      }
    }

    // Actual vararg refs - get alias from varargConnections metadata
    const refsValues = varargInputsById?.refs ?? [];
    const refsConnections = ctx.varargConnections?.get('refs') ?? [];
    for (let i = 0; i < refsValues.length; i++) {
      const value = refsValues[i];
      const conn = refsConnections[i];
      if (value && value.k === 'sig' && conn) {
        // Use alias if available, otherwise fall back to sourceAddress
        const alias = conn.alias ?? conn.sourceAddress;
        allInputEntries.push({ alias, signal: value.id as SigExprId });
      }
    }

    // Step 4: SINGLE PROCESSING LOOP - the ONE code path
    // Process ALL inputs (legacy via shim + actual varargs) identically
    const inputs = new Map<string, SignalType>();
    const inputSignals = new Map<string, SigExprId>();

    for (const { alias, signal } of allInputEntries) {
      const inputType = getSigType(signal);
      inputs.set(alias, inputType);
      inputSignals.set(alias, signal);
    }

    // Step 5: Compile expression using Expression DSL
    const result = compileExpression(exprText, inputs, ctx.b, inputSignals);

    // Step 6 & 7: Handle compilation result
    if (!result.ok) {
      // Compilation failed - format error message
      const err = result.error;
      const positionInfo = err.position
        ? ` at position ${err.position.start}`
        : '';
      const suggestionInfo = err.suggestion
        ? `\nSuggestion: ${err.suggestion}`
        : '';

      throw new Error(
        `Expression ${err.code}: ${err.message}${positionInfo}${suggestionInfo}`
      );
    }

    // Compilation succeeded - return output signal
    const sigId = result.value;
    const outType = ctx.outTypes[0];
    const slot = ctx.b.allocSlot();

    return {
      outputsById: {
        out: { k: 'sig', id: sigId, slot, type: outType, stride: strideOf(outType.payload) },
      },
    };
  },
});
